"""The local SatQuery intent model: question text -> one operation label.

    classifier text -> IntentClassifier.predict() -> IntentPrediction

A small linear classifier - TF-IDF over word 1-2-grams and character 2-5-grams
(word-bounded), then multinomial logistic regression - trained by
``scripts/train_intent_model.py`` on the versioned dataset in
``data/intent/``. Its ONLY job is to name the operation a question asks for.
It computes nothing, chooses no raster, and never sees a coordinate or a date
as such: places and dates are replaced by ``PLACE`` / ``DATE`` before it reads
the question, and the deterministic reader stays authoritative for both.

**The artifact is data, never code.** Training exports the fitted pipeline to
one JSON document - vocabularies, IDF weights, coefficients - and this module
re-implements the two transforms and the softmax in numpy. There is no pickle
anywhere, so loading a model cannot execute anything, and production needs no
scikit-learn. The training script verifies that this implementation reproduces
scikit-learn's probabilities on every dataset example before it writes the
file, and ``tests/test_intent_model.py`` re-checks it.

**The artifact is untrusted input.** Every field is validated on load - format,
the exact label set, shapes, finiteness, sizes - and anything unexpected
refuses the whole model. A refused or missing model is not an outage: the
router then uses the rule-based interpreter alone, which is what M5.5 shipped.

**The output is untrusted too.** A prediction is an :class:`IntentPrediction`
whose label is a closed ``Literal`` and whose confidence is a finite
probability. There is no field that could carry a URL, a path, a command or a
route - only one of eight names and a number.

Purity: no network, no provider, no filesystem access beyond reading the one
artifact file. Imports are stdlib, numpy and pydantic - enforced by a test.
"""

from __future__ import annotations

import gzip
import json
import math
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, get_args

import numpy as np
from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.core.logging import get_logger

logger = get_logger("agent.intent_model")

#: The operations the model may name. Exactly the backend's capabilities plus
#: the two refusals; nothing is listed that the engines cannot do.
IntentLabel = Literal[
    "NDVI",
    "NDWI",
    "NDBI",
    "SAR_BACKSCATTER",
    "TEMPORAL_NDWI",
    "TRUE_COLOR",
    "CLARIFICATION",
    "UNSUPPORTED",
]
INTENT_LABELS: tuple[str, ...] = get_args(IntentLabel)

ARTIFACT_FORMAT = "satquery-intent-model"
ARTIFACT_FORMAT_VERSION = 1

#: The shipped artifact. Generated by ``scripts/train_intent_model.py``.
DEFAULT_ARTIFACT = Path(__file__).parent / "intent_artifacts" / "satquery_intent_v2.json.gz"

#: Refuse an artifact larger than this many features or bytes: a model this
#: size needs tens of thousands, and nothing legitimate needs millions.
_MAX_FEATURES = 500_000
_MAX_ARTIFACT_BYTES = 20_000_000

# The two text transforms, exactly as scikit-learn defines them for the
# configuration training uses (lowercase, no accent stripping, default token
# pattern, char_wb). Changing either here without retraining is caught by the
# equivalence test.
_TOKEN = re.compile(r"(?u)\b\w\w+\b")
_WHITE_SPACES = re.compile(r"\s\s+")


class IntentModelError(ValueError):
    """The artifact is missing, malformed or not one this build understands."""


class IntentPrediction(BaseModel):
    """What the model said: one closed label and how sure it was.

    Validated like any other untrusted output. ``extra="forbid"`` and the
    ``Literal`` label mean nothing else can be carried through it.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    label: IntentLabel
    confidence: float = Field(ge=0.0, le=1.0)

    @field_validator("confidence")
    @classmethod
    def _finite(cls, value: float) -> float:
        if not math.isfinite(value):
            raise ValueError("confidence must be finite")
        return value


def _word_ngrams(text: str, ngram_range: tuple[int, int]) -> list[str]:
    tokens = _TOKEN.findall(text.lower())
    min_n, max_n = ngram_range
    grams: list[str] = []
    for n in range(min_n, max_n + 1):
        for i in range(len(tokens) - n + 1):
            grams.append(" ".join(tokens[i : i + n]))
    return grams


def _char_wb_ngrams(text: str, ngram_range: tuple[int, int]) -> list[str]:
    """scikit-learn's ``char_wb`` analyzer: n-grams inside space-padded words."""

    text = _WHITE_SPACES.sub(" ", text.lower())
    min_n, max_n = ngram_range
    grams: list[str] = []
    for word in text.split():
        padded = f" {word} "
        length = len(padded)
        for n in range(min_n, max_n + 1):
            offset = 0
            grams.append(padded[offset : offset + n])
            while offset + n < length:
                offset += 1
                grams.append(padded[offset : offset + n])
            if offset == 0:  # a word shorter than n is counted once
                break
    return grams


@dataclass(frozen=True)
class _TfidfBlock:
    """One fitted TF-IDF transform: vocabulary, IDF, sublinear TF, L2 norm."""

    analyzer: str
    ngram_range: tuple[int, int]
    index: dict[str, int]
    idf: np.ndarray

    def transform(self, text: str) -> tuple[np.ndarray, np.ndarray]:
        """Column indices and values of the one-row TF-IDF vector."""

        grams = (
            _word_ngrams(text, self.ngram_range)
            if self.analyzer == "word"
            else _char_wb_ngrams(text, self.ngram_range)
        )
        counts: dict[int, int] = {}
        for gram in grams:
            column = self.index.get(gram)
            if column is not None:
                counts[column] = counts.get(column, 0) + 1
        if not counts:
            return np.empty(0, dtype=np.int64), np.empty(0, dtype=np.float64)
        columns = np.fromiter(counts.keys(), dtype=np.int64, count=len(counts))
        tf = np.fromiter(counts.values(), dtype=np.float64, count=len(counts))
        values = (1.0 + np.log(tf)) * self.idf[columns]
        norm = float(np.sqrt(np.dot(values, values)))
        return columns, (values / norm if norm > 0 else values)


class IntentClassifier:
    """The loaded model. Construct through :func:`load_intent_classifier`."""

    def __init__(
        self,
        *,
        labels: tuple[str, ...],
        blocks: tuple[_TfidfBlock, ...],
        coef: np.ndarray,
        intercept: np.ndarray,
        threshold: float,
        version: str,
        metadata: dict[str, Any],
    ) -> None:
        self.labels = labels
        self._blocks = blocks
        self._coef = coef
        self._intercept = intercept
        #: The confidence below which a prediction is not acted on. Chosen on
        #: the validation split when this artifact was trained, and shipped
        #: WITH it, because a threshold is only meaningful for its own model.
        self.threshold = threshold
        self.version = version
        self.metadata = metadata

    def probabilities(self, text: str) -> np.ndarray:
        """Softmax over the labels, in ``self.labels`` order."""

        scores = self._intercept.copy()
        offset = 0
        for block in self._blocks:
            columns, values = block.transform(text)
            if columns.size:
                scores += self._coef[:, offset + columns] @ values
            offset += len(block.index)
        scores -= scores.max()
        exp = np.exp(scores)
        return exp / exp.sum()

    def predict(self, text: str) -> IntentPrediction:
        """The most probable label, validated before it leaves this module."""

        probabilities = self.probabilities(text)
        best = int(np.argmax(probabilities))
        return IntentPrediction(
            label=self.labels[best],  # type: ignore[arg-type]
            confidence=float(probabilities[best]),
        )


# --------------------------------------------------------------------------- #
# Loading - every field checked, because the file is input
# --------------------------------------------------------------------------- #


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise IntentModelError(message)


def _finite_vector(raw: Any, length: int | None, name: str) -> np.ndarray:
    _require(isinstance(raw, list), f"{name} must be a list")
    array = np.asarray(raw, dtype=np.float64)
    _require(array.ndim == 1, f"{name} must be one-dimensional")
    if length is not None:
        _require(array.shape[0] == length, f"{name} has the wrong length")
    _require(bool(np.all(np.isfinite(array))), f"{name} must be finite")
    return array


def _ngram_range(raw: Any, name: str) -> tuple[int, int]:
    _require(
        isinstance(raw, list) and len(raw) == 2 and all(type(v) is int for v in raw),
        f"{name}.ngram_range must be two integers",
    )
    low, high = raw
    _require(1 <= low <= high <= 8, f"{name}.ngram_range is out of bounds")
    return low, high


def _block(raw: Any, name: str, analyzer: str) -> _TfidfBlock:
    _require(isinstance(raw, dict), f"{name} must be an object")
    _require(raw.get("analyzer") == analyzer, f"{name}.analyzer must be {analyzer!r}")
    vocabulary = raw.get("vocabulary")
    _require(
        isinstance(vocabulary, list) and all(isinstance(t, str) for t in vocabulary),
        f"{name}.vocabulary must be a list of strings",
    )
    _require(len(vocabulary) == len(set(vocabulary)), f"{name}.vocabulary has duplicates")
    idf = _finite_vector(raw.get("idf"), len(vocabulary), f"{name}.idf")
    _require(bool(np.all(idf > 0)), f"{name}.idf must be positive")
    return _TfidfBlock(
        analyzer=analyzer,
        ngram_range=_ngram_range(raw.get("ngram_range"), name),
        index={term: position for position, term in enumerate(vocabulary)},
        idf=idf,
    )


def parse_artifact(document: Any) -> IntentClassifier:
    """Build a classifier from an artifact document, or refuse it."""

    _require(isinstance(document, dict), "the artifact must be a JSON object")
    _require(document.get("format") == ARTIFACT_FORMAT, "not a SatQuery intent model")
    _require(
        document.get("format_version") == ARTIFACT_FORMAT_VERSION,
        "unsupported intent model format version",
    )
    labels = document.get("labels")
    _require(
        isinstance(labels, list) and sorted(labels) == sorted(INTENT_LABELS)
        and len(labels) == len(INTENT_LABELS),
        "the artifact's labels must be exactly the supported intents",
    )
    features = document.get("features")
    _require(isinstance(features, dict), "features must be an object")
    blocks = (
        _block(features.get("word"), "features.word", "word"),
        _block(features.get("char"), "features.char", "char_wb"),
    )
    width = sum(len(block.index) for block in blocks)
    _require(0 < width <= _MAX_FEATURES, "the feature count is out of bounds")

    classifier = document.get("classifier")
    _require(isinstance(classifier, dict), "classifier must be an object")
    coef_raw = classifier.get("coef")
    _require(
        isinstance(coef_raw, list) and len(coef_raw) == len(labels),
        "coef must have one row per label",
    )
    coef = np.vstack([_finite_vector(row, width, "coef row") for row in coef_raw])
    intercept = _finite_vector(classifier.get("intercept"), len(labels), "intercept")

    threshold = document.get("threshold")
    _require(
        isinstance(threshold, (int, float)) and not isinstance(threshold, bool)
        and math.isfinite(threshold) and 0.0 < threshold < 1.0,
        "threshold must be a probability strictly between 0 and 1",
    )
    version = document.get("model_version")
    _require(
        isinstance(version, str) and re.fullmatch(r"[A-Za-z0-9._-]{1,64}", version) is not None,
        "model_version must be a short identifier",
    )
    metadata = document.get("metadata")
    _require(isinstance(metadata, dict), "metadata must be an object")

    return IntentClassifier(
        labels=tuple(labels),
        blocks=blocks,
        coef=coef,
        intercept=intercept,
        threshold=float(threshold),
        version=version,
        metadata=metadata,
    )


def read_artifact(path: Path) -> IntentClassifier:
    """Read and validate an artifact file (gzip-compressed or plain JSON)."""

    raw = path.read_bytes()
    _require(len(raw) <= _MAX_ARTIFACT_BYTES, "the artifact file is too large")
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
        _require(len(raw) <= 5 * _MAX_ARTIFACT_BYTES, "the artifact expands too far")
    try:
        document = json.loads(raw)
    except ValueError as exc:
        raise IntentModelError("the artifact is not valid JSON") from exc
    return parse_artifact(document)


@lru_cache(maxsize=1)
def load_intent_classifier(path: Path | None = None) -> IntentClassifier | None:
    """The shipped model, loaded once per process - or ``None``.

    ``None`` is a supported state, not an error: the router then interprets
    with the rules alone. The reason is logged by class, never by content.
    """

    target = path or DEFAULT_ARTIFACT
    try:
        classifier = read_artifact(target)
    except (OSError, IntentModelError, ValueError) as exc:
        logger.warning(
            "Intent model unavailable (%s); interpreting with the rules alone",
            type(exc).__name__,
        )
        return None
    logger.info(
        "Intent model %s loaded (%d labels, threshold %.2f)",
        classifier.version,
        len(classifier.labels),
        classifier.threshold,
    )
    return classifier
